# -*- coding: utf-8 -*-
"""Pong rl-baselines-zoo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dNtyLp3QMUW-uYf4S6rctSIR7-WeuRvT

# RL Baselines3 Zoo: Training in Colab



Github Repo: [https://github.com/DLR-RM/rl-baselines3-zoo](https://github.com/DLR-RM/rl-baselines3-zoo)

Stable-Baselines3 Repo: [https://github.com/DLR-RM/rl-baselines3-zoo](https://github.com/DLR-RM/stable-baselines3)


# Install Dependencies
"""

!apt-get install swig cmake ffmpeg freeglut3-dev xvfb

"""## Clone RL Baselines3 Zoo Repo"""

!git clone --recursive https://github.com/DLR-RM/rl-baselines3-zoo

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/rl-baselines3-zoo/

"""### Install pip dependencies"""

!pip install -r requirements.txt

"""## Train an RL Agent


The train agent can be found in the `logs/` folder.

To train it on Pong (Atari), I just have to pass `--env PongNoFrameskip-v4`
I usually retrained the model by refercing the previous trained model made prior.
"""

!python train.py --algo dqn --env PongNoFrameskip-v4 -i logs/dqn/PongNoFrameskip-v4_1/PongNoFrameskip-v4.zip -n 5000

"""#### Evaluate trained agent


You can remove the `--folder logs/` to evaluate pretrained agent.
"""

!python enjoy.py --algo dqn --env PongNoFrameskip-v4 --no-render --n-timesteps 1000 --folder logs/

"""### Record  a Video"""

# Set up display; otherwise rendering will fail
import os
os.system("Xvfb :1 -screen 0 1024x768x24 &")
os.environ['DISPLAY'] = ':1'

!python -m utils.record_video --algo dqn --env PongNoFrameskip-v4 --exp-id 0 -f logs/ -n 1000

"""### Display the video"""

import base64
from pathlib import Path

from IPython import display as ipythondisplay

def show_videos(video_path='', prefix=''):
  """
  Taken from https://github.com/eleurent/highway-env

  :param video_path: (str) Path to the folder containing videos
  :param prefix: (str) Filter the video, showing only the only starting with this prefix
  """
  html = []
  for mp4 in Path(video_path).glob("{}*.mp4".format(prefix)):
      video_b64 = base64.b64encode(mp4.read_bytes())
      html.append('''<video alt="{}" autoplay 
                    loop controls style="height: 400px;">
                    <source src="data:video/mp4;base64,{}" type="video/mp4" />
                </video>'''.format(mp4, video_b64.decode('ascii')))
  ipythondisplay.display(ipythondisplay.HTML(data="<br>".join(html)))

show_videos(video_path='logs/videos/', prefix='dqn')